### ISSUE TITLE
你的react 通用列表组件封装源码404了?能否更新一下源码地址

### ISSUE THREAD

**Issue by theSouthSea** [rxliuli/blog#45]
你的react 通用列表组件封装博客的源码404了?
地址是: https://blog.rxliuli.com/p/c55a6470683e498f92ba05d7ff710b3a/#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

封装的很不错, 想看一下源码, 有劳大神更新一下.

**Comment by rxliuli** [comment]
不幸的是，吾辈也找不到这个项目了，也许还在某块旧硬盘中，但忘记具体放在哪儿了😮‍💨
